import raw from './calibrationTargets.json';

/**
 * Calibration targets of the default US release, grouped by source table
 * and measured concept. Generated by scripts/extract_calibration_targets.py
 * from the release's calibration_diagnostics.json; do not edit the JSON by
 * hand.
 */
export interface CalibrationGroup {
  concept: string;
  sourceFamily: string;
  sourceTable: string;
  sourceUrl: string;
  nationalCount: number;
  stateCount: number;
  districtCount: number;
  otherCount: number;
  targetCount: number;
  unit: 'usd' | 'count' | null;
  withinTenPctShare: number;
  nationalValue: number | null;
  periods: number[];
}

export interface CalibrationLevelCounts {
  national: number;
  state: number;
  district: number;
  /** Build-internal constraints with no administrative geography */
  other: number;
}

export interface CalibrationData {
  /** The release the policyengine Python package pins as the US default */
  releaseId: string;
  policyenginePackageVersion: string | null;
  /** The build whose weights the release carries (itself, or a parent) */
  calibrationReleaseId: string;
  calibratedAt: string | null;
  households: number;
  totalTargets: number;
  withinTenPctShare: number;
  levelCounts: CalibrationLevelCounts;
  targets: CalibrationGroup[];
}

export const usCalibration = raw as CalibrationData;

/** Targets that bind a published figure at a geography (not build-internal). */
export function administrativeTargetCount(levels: CalibrationLevelCounts): number {
  return levels.national + levels.state + levels.district;
}

/** Target count per source family, largest first. */
export function targetCountsByFamily(data: CalibrationData): [string, number][] {
  const counts = new Map<string, number>();
  for (const g of data.targets) {
    counts.set(g.sourceFamily, (counts.get(g.sourceFamily) ?? 0) + g.targetCount);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]);
}

export function formatPercent(share: number): string {
  return `${(share * 100).toFixed(1)}%`;
}

/** "a, b, and c" */
export function joinList(items: string[]): string {
  if (items.length <= 1) return items.join('');
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`;
}

/** "447 national and 5,211 state-level targets" */
export function describeLevels(levels: CalibrationLevelCounts): string {
  const parts = [
    levels.national > 0 ? `${levels.national.toLocaleString()} national` : null,
    levels.state > 0 ? `${levels.state.toLocaleString()} state-level` : null,
    levels.district > 0 ? `${levels.district.toLocaleString()} congressional district` : null,
  ].filter((p): p is string => p !== null);
  return `${joinList(parts)} targets`;
}
