// Auto-generated by scripts/count_params.py
// Last updated: 2026-02-10
export const parameterStats = {
  generatedAt: '2026-02-10',
  us: { yamlFiles: 3544, currentParams: 29928, historicalValues: 49457 },
  uk: { yamlFiles: 448, currentParams: 835, historicalValues: 2760 },
  combined: { yamlFiles: 3992, currentParams: 30763, historicalValues: 52217 },
};
